# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gladiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('speciality', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('skin_color', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('planet', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='gladiator',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladiators.Profession'),
        ),
        migrations.AddField(
            model_name='gladiator',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladiators.Race'),
        ),
        migrations.AddField(
            model_name='gladiator',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladiators.Species'),
        ),
    ]
